### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by UFO-6666** [dalong982242260/AndroidMarqueeView#12]
java.lang.OutOfMemoryError: Failed to allocate a 4941016 byte allocation with 4140292 free bytes and 3MB until OOM
	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
	at java.lang.StringBuilder.append(StringBuilder.java:216)
	at com.demo.demo.view.MarqueeView.onDraw(MarqueeView.java:176)
	at android.view.View.draw(View.java:15253)
	at android.view.View.updateDisplayListIfDirty(View.java:14189)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
	at android.view.View.updateDisplayListIfDirty(View.java:14149)
	at android.view.View.getDisplayList(View.java:14211)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2580)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2402)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2032)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5258)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by UFO-6666** [comment]
string = string + content;
